name: Run pytest in pytrajplot

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  blueprint-pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Create env from pinned reqs
      run: |
        conda activate
        conda  env create --name pytrajplot --file requirements/environment.yml
    - name: Install project into env
      run: |
        conda run --name pytrajplot pip install --no-deps .
    - name: Run pytest
      run: |
        conda run --name pytrajplot pytest run --all-files
